# Generated by Django 2.2.5 on 2021-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionMachineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_model', models.CharField(blank=True, max_length=8, null=True, verbose_name='注塑机型号')),
                ('screw_type', models.CharField(blank=True, max_length=1, null=True, verbose_name='螺杆类型')),
                ('screw_diameter', models.IntegerField(blank=True, null=True, verbose_name='螺杆直径')),
                ('screw_LD_ratio', models.IntegerField(blank=True, null=True, verbose_name='螺杆长径比')),
                ('shot_size_therotetical', models.IntegerField(blank=True, null=True, verbose_name='理论容量')),
                ('injection_weight_PS', models.IntegerField(blank=True, null=True, verbose_name='射出量')),
                ('injection_speed', models.FloatField(blank=True, null=True, verbose_name='射出速度')),
                ('plasticizing_capacity', models.IntegerField(blank=True, null=True, verbose_name='塑化能力')),
                ('injection_pressure', models.IntegerField(blank=True, null=True, verbose_name='射出压力')),
                ('screw_speed', models.IntegerField(blank=True, null=True, verbose_name='螺杆转速')),
                ('clamping_force', models.IntegerField(blank=True, null=True, verbose_name='锁模力')),
                ('clamping_stroke', models.IntegerField(blank=True, null=True, verbose_name='锁模行程')),
                ('space_between_tie_bars_x', models.IntegerField(blank=True, null=True, verbose_name='拉杆间隔_x')),
                ('space_between_tie_bars_y', models.IntegerField(blank=True, null=True, verbose_name='拉杆间隔_y')),
                ('max_mold_height', models.IntegerField(blank=True, null=True, verbose_name='最大模厚')),
                ('min_mold_height', models.IntegerField(blank=True, null=True, verbose_name='最小模厚')),
                ('toggle_stroke', models.IntegerField(blank=True, null=True, verbose_name='开模行程')),
                ('ejector_tonnage', models.IntegerField(blank=True, null=True, verbose_name='顶出力')),
                ('ejector_number', models.IntegerField(blank=True, null=True, verbose_name='顶出杆根数')),
                ('max_pump_pressure', models.FloatField(blank=True, null=True, verbose_name='最大泵压力')),
                ('pump_motor_power', models.IntegerField(blank=True, null=True, verbose_name='马达输出功率')),
                ('heater_power', models.FloatField(blank=True, null=True, verbose_name='加热器输出功率')),
                ('machine_length', models.FloatField(blank=True, null=True, verbose_name='机器外形长度')),
                ('machine_width', models.IntegerField(blank=True, null=True, verbose_name='机器外形宽度')),
                ('machine_height', models.FloatField(blank=True, null=True, verbose_name='机器外形高度')),
                ('machine_weight', models.FloatField(blank=True, null=True, verbose_name='机械重量')),
                ('container_capacity', models.IntegerField(blank=True, null=True, verbose_name='贮料器容量')),
                ('hppper_capacity', models.IntegerField(blank=True, null=True, verbose_name='料简体积')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '注塑机参数',
                'db_table': 'injection_machine_info',
                'managed': True,
            },
        ),
    ]
