# Generated by Django 2.2.5 on 2021-05-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_area_min', models.IntegerField(blank=True, null=True, verbose_name='零件投影面积min')),
                ('projection_area_max', models.IntegerField(blank=True, null=True, verbose_name='零件投影面积max')),
                ('number_die_caves', models.IntegerField(blank=True, null=True, verbose_name='模穴数')),
            ],
            options={
                'verbose_name': '模穴数推荐',
                'db_table': 'number_die_caves',
                'managed': True,
            },
        ),
    ]
