# Generated by Django 2.2.5 on 2021-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionTool', '0002_numbercaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='pressure_in_mold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='材料类型')),
                ('pressure_in_mold', models.IntegerField(blank=True, null=True, verbose_name='模内压力')),
                ('factor_min_adding_glass_fiber', models.FloatField(blank=True, null=True, verbose_name='加玻纤系数min')),
                ('factor_max_adding_glass_fiber', models.FloatField(blank=True, null=True, verbose_name='加玻纤系数max')),
            ],
            options={
                'verbose_name': '模内压力',
                'db_table': 'pressure_in_mold',
                'managed': True,
            },
        ),
    ]
