# Generated by Django 2.2.5 on 2021-05-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionTool', '0003_pressure_in_mold'),
    ]

    operations = [
        migrations.CreateModel(
            name='density_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='材料类型')),
                ('density_min', models.FloatField(blank=True, null=True, verbose_name='密度min')),
                ('density_max', models.FloatField(blank=True, null=True, verbose_name='密度max')),
            ],
            options={
                'verbose_name': '材料密度',
                'db_table': 'density_material',
                'managed': True,
            },
        ),
    ]
