# Generated by Django 2.2.5 on 2021-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionTool', '0004_density_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='die_edge_distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_length_min', models.IntegerField(blank=True, null=True, verbose_name='零件长边_min')),
                ('product_length_max', models.IntegerField(blank=True, null=True, verbose_name='零件长边_max')),
                ('die_edge_distance', models.IntegerField(blank=True, null=True, verbose_name='模具边距')),
            ],
            options={
                'verbose_name': '模具边距',
                'db_table': 'die_edge_distance',
                'managed': True,
            },
        ),
    ]
