# Generated by Django 2.2.5 on 2021-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionTool', '0005_die_edge_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_utilization_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_net_weight_min', models.IntegerField(blank=True, null=True, verbose_name='零件净重_min')),
                ('product_net_weight_max', models.IntegerField(blank=True, null=True, verbose_name='零件净重_max')),
                ('material_utilization_rate', models.FloatField(blank=True, null=True, verbose_name='材料利用率')),
            ],
            options={
                'verbose_name': '材料利用率',
                'db_table': 'material_utilization_rate',
                'managed': True,
            },
        ),
    ]
