# Generated by Django 2.2.5 on 2021-06-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InjectionTool', '0006_material_utilization_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='density_material',
            name='pressure_in_mold',
            field=models.IntegerField(blank=True, null=True, verbose_name='模内压力'),
        ),
    ]
